FROM containerbase/buildpack@sha256:3adec8196bcec7d1b822c24938347edaf9572d575c71e13aefa22fd80bbeb2ef

# renovate: datasource=docker versioning=docker
RUN install-tool node 14.16.1 \
# renovate: datasource=npm
  && install-tool yarn 1.22.10